# Generated by Django 5.2.14 on 2026-05-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('apelido_local', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fuso_horario', models.CharField(default='America/Sao_Paulo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('local_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_evento', models.CharField(choices=[('trabalho', 'Trabalho'), ('estudo', 'Estudo'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.localizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrevisaoClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.IntegerField()),
                ('velocidade_vento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicao_climatica', models.CharField(max_length=100)),
                ('probabilidade_chuva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='core.localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('chuva', 'Chuva'), ('tempestade', 'Tempestade'), ('vento_forte', 'Vento forte'), ('calor_extremo', 'Calor extremo'), ('frio_extremo', 'Frio extremo'), ('outro', 'Outro')], max_length=30)),
                ('mensagem', models.TextField()),
                ('data_hora_envio', models.DateTimeField()),
                ('status_leitura', models.CharField(choices=[('nao_lido', 'Não lido'), ('lido', 'Lido')], default='nao_lido', max_length=20)),
                ('antecedencia', models.IntegerField(help_text='Antecedência em minutos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.eventocalendario')),
                ('previsao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='core.previsaoclimatica')),
            ],
        ),
        migrations.AddField(
            model_name='localizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuva', models.BooleanField(default=True)),
                ('tempestade', models.BooleanField(default=True)),
                ('vento_forte', models.BooleanField(default=True)),
                ('calor_extremo', models.BooleanField(default=True)),
                ('frio_extremo', models.BooleanField(default=True)),
                ('antecedencia_padrao', models.IntegerField(default=60, help_text='Antecedência padrão em minutos')),
                ('notificacao_push_ativa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_alerta', to='core.usuario')),
            ],
        ),
    ]
